/*
 * InfiniClick — simulated layout ratios (generated by simul.html).
 *
 * Per-LAYOUT constants from the real ball/brick physics. For each board shape
 * (grid, staggered, ring, pyramid): clearSecondsByBallCount (how fast N balls
 * sweep a one-shot board — the geometry-limited floor) and hitsPerSecondPerBall
 * (the EFFECTIVE damaging-hit rate per ball on a full high-HP board — the
 * damage-limited rate, which DPS = rate · ball-power feeds). stats.html picks a
 * layout by universe (layoutForUniverse). Re-generate whenever the grid, the
 * layouts or the physics change.
 */
window.IC = window.IC || {};
IC.sim = {
  "layout": {
    "field": 1000,
    "cols": 6,
    "rows": 4,
    "cell": 166.67,
    "ballR": 26.67,
    "blocks": 24,
    "ballSpeed": 520
  },
  "layouts": {
    "0": {
      "name": "grid",
      "hitsPerSecondPerBall": 0.392,
      "clearSecondsByBallCount": {
        "1": 96.454,
        "2": 38.118,
        "3": 19.128,
        "4": 15.429,
        "5": 10.245,
        "6": 9.121,
        "7": 7.771,
        "8": 6.162,
        "9": 5.609,
        "10": 5.016,
        "11": 3.709,
        "12": 3.59,
        "13": 3.308,
        "14": 3.519,
        "15": 2.654,
        "16": 2.389,
        "17": 2.269,
        "18": 2.309,
        "19": 1.729,
        "20": 1.784
      }
    },
    "1": {
      "name": "staggered",
      "hitsPerSecondPerBall": 0.548,
      "clearSecondsByBallCount": {
        "1": 88.672,
        "2": 32.297,
        "3": 17.994,
        "4": 13.394,
        "5": 9.325,
        "6": 7.974,
        "7": 6.955,
        "8": 5.441,
        "9": 4.165,
        "10": 3.917,
        "11": 3.371,
        "12": 3.231,
        "13": 3.012,
        "14": 2.779,
        "15": 2.339,
        "16": 2.717,
        "17": 1.938,
        "18": 1.828,
        "19": 1.646,
        "20": 1.832
      }
    },
    "2": {
      "name": "ring",
      "hitsPerSecondPerBall": 1.47,
      "clearSecondsByBallCount": {
        "1": 63.316,
        "2": 20.977,
        "3": 14.913,
        "4": 10.069,
        "5": 8.034,
        "6": 6.088,
        "7": 4.838,
        "8": 4.646,
        "9": 3.637,
        "10": 3.341,
        "11": 2.894,
        "12": 2.598,
        "13": 2.535,
        "14": 2.542,
        "15": 2.244,
        "16": 1.774,
        "17": 1.736,
        "18": 1.604,
        "19": 1.611,
        "20": 1.469
      }
    },
    "3": {
      "name": "pyramid",
      "hitsPerSecondPerBall": 0.595,
      "clearSecondsByBallCount": {
        "1": 78.981,
        "2": 33.142,
        "3": 23.418,
        "4": 15.187,
        "5": 11.967,
        "6": 8.757,
        "7": 8.843,
        "8": 6.746,
        "9": 6.019,
        "10": 4.971,
        "11": 4.81,
        "12": 4.117,
        "13": 4.244,
        "14": 3.672,
        "15": 3.146,
        "16": 3.077,
        "17": 2.559,
        "18": 2.866,
        "19": 2.826,
        "20": 2.353
      }
    }
  }
};
