/*
 * InfiniClick — simulated layout ratios (generated by simul.html).
 *
 * One constant per LAYOUT from the real ball/brick physics: hitsPerSecondPerBall,
 * the EFFECTIVE damaging-hit rate per ball on a full high-HP board (DPS = rate ·
 * ball-power). hpPercent = rate / grid-rate × 100 is the suggested per-layout HP%
 * (mirror it in config.js LAYOUT_HP_PERCENT so all layouts clear in a similar
 * time). stats.html reads the rate to turn ball power into a clear time, and picks
 * the layout by universe. Re-generate whenever the grid, layouts or physics change.
 */
window.IC = window.IC || {};
IC.sim = {
  "layout": {
    "field": 1000,
    "cols": 6,
    "rows": 4,
    "cell": 166.67,
    "ballR": 26.67,
    "blocks": 24,
    "ballSpeed": 520
  },
  "layouts": {
    "0": {
      "name": "grid",
      "hitsPerSecondPerBall": 0.37,
      "hpPercent": 100
    },
    "1": {
      "name": "staggered",
      "hitsPerSecondPerBall": 0.557,
      "hpPercent": 151
    },
    "2": {
      "name": "ring",
      "hitsPerSecondPerBall": 1.53,
      "hpPercent": 414
    },
    "3": {
      "name": "pyramid",
      "hitsPerSecondPerBall": 0.588,
      "hpPercent": 159
    }
  }
};
