/*
 * InfiniClick — simulated layout ratios (generated by simul.html).
 *
 * Purely geometric measurements of the CURRENT board layout: how fast balls
 * physically sweep a board clean. Re-generate whenever the grid or physics
 * changes. Consumed by stats.html to turn the economy into a time-per-level.
 */
window.IC = window.IC || {};
IC.sim = {
  "layout": {
    "W": 390,
    "H": 620,
    "cols": 6,
    "rows": 4,
    "cell": 65,
    "ballR": 10.4,
    "blocks": 24,
    "ballSpeed": 200
  },
  "hitsPerSecondPerBall": 20.23,
  "clearSecondsByBallCount": {
    "1": 152.402,
    "2": 60.601,
    "3": 34.523,
    "4": 22.246,
    "5": 17.144,
    "6": 16.53,
    "7": 12.866,
    "8": 10.071,
    "9": 7.507,
    "10": 7.258
  }
};
